// <auto-generated />
using System;
using InscriptionEtudiant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InscriptionEtudiant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803113216_CreateAdmission")]
    partial class CreateAdmission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InscriptionEtudiant.Models.Administrateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Administrateurs");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministrateurId")
                        .HasColumnType("int");

                    b.Property<int>("ChoixFiliereId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateDecision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("DossierInscriptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministrateurId");

                    b.HasIndex("ChoixFiliereId");

                    b.HasIndex("DossierInscriptionId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Candidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNE")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.ChoixFiliere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DossierInscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("FiliereId")
                        .HasColumnType("int");

                    b.Property<int>("OrdreChoix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DossierInscriptionId");

                    b.HasIndex("FiliereId");

                    b.ToTable("ChoixFilieres");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chemin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<int>("DossierInscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DossierInscriptionId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.DossierInscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatutActuel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId")
                        .IsUnique();

                    b.ToTable("DossierInscriptions");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebutInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.HistoriqueStatut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministrateurId")
                        .HasColumnType("int");

                    b.Property<string>("AncienStatut")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("datetime2");

                    b.Property<int>("DossierInscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("NouveauStatut")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdministrateurId");

                    b.HasIndex("DossierInscriptionId");

                    b.ToTable("HistoriqueStatuts");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.ParcoursAcademique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeBac")
                        .HasColumnType("int");

                    b.Property<int?>("DossierInscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("MentionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NoteNationale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NoteRegionale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SerieBacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DossierInscriptionId")
                        .IsUnique()
                        .HasFilter("[DossierInscriptionId] IS NOT NULL");

                    b.HasIndex("MentionId");

                    b.HasIndex("SerieBacId");

                    b.ToTable("ParcoursAcademiques");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.SerieBac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SerieBacs");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Admission", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.Administrateur", "Administrateur")
                        .WithMany()
                        .HasForeignKey("AdministrateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InscriptionEtudiant.Models.ChoixFiliere", "ChoixFiliere")
                        .WithMany()
                        .HasForeignKey("ChoixFiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InscriptionEtudiant.Models.DossierInscription", "DossierInscription")
                        .WithMany()
                        .HasForeignKey("DossierInscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrateur");

                    b.Navigation("ChoixFiliere");

                    b.Navigation("DossierInscription");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.ChoixFiliere", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.DossierInscription", "DossierInscription")
                        .WithMany("ChoixFilieres")
                        .HasForeignKey("DossierInscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InscriptionEtudiant.Models.Filiere", "Filiere")
                        .WithMany()
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierInscription");

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Document", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.DossierInscription", "DossierInscription")
                        .WithMany("Documents")
                        .HasForeignKey("DossierInscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierInscription");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.DossierInscription", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.Candidat", "Candidat")
                        .WithOne("DossierInscription")
                        .HasForeignKey("InscriptionEtudiant.Models.DossierInscription", "CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.HistoriqueStatut", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.Administrateur", "Administrateur")
                        .WithMany()
                        .HasForeignKey("AdministrateurId");

                    b.HasOne("InscriptionEtudiant.Models.DossierInscription", "DossierInscription")
                        .WithMany("HistoriqueStatuts")
                        .HasForeignKey("DossierInscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrateur");

                    b.Navigation("DossierInscription");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.ParcoursAcademique", b =>
                {
                    b.HasOne("InscriptionEtudiant.Models.DossierInscription", "DossierInscription")
                        .WithOne("ParcoursAcademique")
                        .HasForeignKey("InscriptionEtudiant.Models.ParcoursAcademique", "DossierInscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InscriptionEtudiant.Models.Mention", "Mention")
                        .WithMany()
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InscriptionEtudiant.Models.SerieBac", "SerieBac")
                        .WithMany()
                        .HasForeignKey("SerieBacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DossierInscription");

                    b.Navigation("Mention");

                    b.Navigation("SerieBac");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.Candidat", b =>
                {
                    b.Navigation("DossierInscription");
                });

            modelBuilder.Entity("InscriptionEtudiant.Models.DossierInscription", b =>
                {
                    b.Navigation("ChoixFilieres");

                    b.Navigation("Documents");

                    b.Navigation("HistoriqueStatuts");

                    b.Navigation("ParcoursAcademique");
                });
#pragma warning restore 612, 618
        }
    }
}
